print('=' * 30)
print('<-- Car consortium -->')
print('=' * 30)
day = int(input('How many rental days: '))
km = float(input('How many kilometers did you drive: '))
print('=' * 30)
print('<-- Total payable -->')
print('=' * 30)
print('Cost for {} days: {:.2f}$'.format(day, day * 60))
print('Cost for {}km: {:.2f}$'.format(km, km * 0.15))
print('Total payable: {:.2f}$'.format(day * 60 + km * 0.15))
print('-' * 30)
