print('-----------------------')
print('<-- Type the number -->')
print('-----------------------')
number = int(input('Type the number: '))
print('-------------------------------')
print('<-- Dobro, Triplo and raiz² -->')
print('-------------------------------')
print('Dobro no number {}: {}'.format(number, number * 2))
print('Triplo do number {}: {}'.format(number, number * 3))
print('Raiz quadrada do number {}: {:.2f}'.format(number, number**(1/2)))
