print('=' * 30)
print('<-- Playing with Count method -->')
print('=' * 30)
name = str(input('Enter with a name: '))
first = name.find('A')
last = name.rfind('A')
print('How often does the letter A appear: {}'.format(name.count('A')))
print('What position does this letter appear for the first time: ', end='')
print(first)
print('What position does this letter appear for the last time: ', end='')
print(last)
print('-' * 30)
