print('=' * 20)
print('<-- Playing with string -->')
print('=' * 20)
name = str(input('Say a complete name: ')).strip()
print('The name with small print: {}'.format(name.lower()))
print('The name with big print: {}'.format(name.upper()))
print('Total characters: {}'.format(len(name) - name.count(' ')))
first = name.split()
print('Total first name characters: {}'.format(len(first[0])))
print('-' * 30)
