print('----------------------')
print('     <-- Média -->')
print('----------------------')
nota1 = float(input('Digite a primera nota: '))
nota2 = float(input('Digite a segunda nota: '))
print('-------------------------')
print('   <-- Média Final -->')
print('-------------------------')
print('Nota 1: {}'.format(nota1))
print('Nota 2: {}'.format(nota2))
print('Média entre as notas: {}'.format((nota1 + nota2) / 2))
