print('===================================')
print('<-- Enter the number of meters --> ')
print('===================================')
meters = float(input('How many meters: '))
print('\n=================================')
print('        <- Conversion -->')
print('=================================')
print('{} meters for centimeter: {}'.format(meters, meters * 100))
print('{} meters for millimeter: {}'.format(meters, meters * 1000))
print('=========================================')
