print('============================')
print('<-- Salary increase Day -->')
print('============================')
salary = float(input('Enter your monthly salary R$: '))
increase = salary + (0.15 * salary)
print('===========================')
print('<-- Increase of 15% -->')
print('==========================')
print('Your original salary: {}$'.format(salary))
print('You salary with 15% increase: {}$'.format(increase))
print('======================================')
