# tabuada de Vezes
print('===============================')
print('<-- Times table of Happines -->')
print('===============================')
number = int(input('Enter the number: '))
print('\n\n============================')
print('<-- Showing Times Talbes -->')
print('=============================')
print('{}x1:  {}'.format(number, number * 1))
print('{}x2:  {}'.format(number, number * 2))
print('{}x3:  {}'.format(number, number * 3))
print('{}x4:  {}'.format(number, number * 4))
print('{}x5:  {}'.format(number, number * 5))
print('{}x6:  {}'.format(number, number * 6))
print('{}x7:  {}'.format(number, number * 7))
print('{}x8:  {}'.format(number, number * 8))
print('{}x9:  {}'.format(number, number * 9))
print('{}x10: {}'.format(number, number * 10))
print('=======================')
