print('--------------------------')
print('<-- Type the number -->')
print('--------------------------')
number = int(input('Digite um número inteiro: '))
print('-----------------------------------')
print('<-- Sucessor and Antecessor -->')
print('-----------------------------------')
print('Sucessor do number {}: {}'.format(number, number + 1))
print('Antecessor do number {}: {}'.format(number, number - 1))
