print('---------------------\n')
print('<-- Challenge 02 -->\n')
print('--------------------\n')
day = input('Dia = ')
month = input('Mês = ')
year = input('Ano = ')
print('---------------\n')
print(' <-- Date -->\n')
print('---------------')
print('Você nasceu no dia', day, 'de ', month, 'de ', year, '. Correto?')
