print('====================')
print('<-- Discount of prices -->')
print('========================')
price = float(input('How much does the product cost R$: '))
discount = price - (0.05 * price)
print('=======================')
print('<-- Discount of 5% -->')
print('=======================')
print('Original price: {}$'.format(price))
print('Price with discount of 5%: {:.2f}$'.format(discount))
print('==================================')
