print('\033[33m=' * 40)
print('\t<-- Car consortium -->')
print('=' * 40)
day = int(input('How many rental days: '))
km = float(input('How many kilometers did you drive: '))
print('=' * 40)
print('\t<-- Total payable -->')
print('=' * 40)
print('Cost for {} days: {:.2f}$'.format(day, day * 60))
print('Cost for {}km: {:.2f}$'.format(km, km * 0.15))
print('Total payable: {:.2f}$'.format(day * 60 + km * 0.15))
print('-' * 40)
