print('=' * 30)
print('<-- Playing with Split method -->')
print('=' * 30)
name = str(input('Enter with a name: ')).strip()
firstandlast = name.split()
print('First name: {}'.format(firstandlast[0]))
print('Last name: {}'.format(firstandlast[len(firstandlast) - 1]))
print('-' * 30)
